Move most of min_requirements.py to the framework
Mbed-TLS/mbedtls-framework pull request #105
Opened 2024-12-19 15:46 UTC by valeriosetti

## Description

Resolves issue #86 

`development` PR:
`mbedtls-3.6` PR:

## PR checklist

Please add the numbers (or links) of the associated pull requests for consuming branches. You can omit branches where this pull request is not needed.

- [ ] **crypto PR** Mbed-TLS/TF-PSA-Crypto#
- [ ] **development PR** Mbed-TLS/mbedtls#
- [ ] **3.6 PR** Mbed-TLS/mbedtls#

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2025-01-10 09:35 UTC, Harry-Ramsey approved these changes
LGTM.

2025-01-10 15:24 UTC, ronald-cron-arm requested changes
Two things I am not sure about.

2025-01-10 15:24 UTC, ronald-cron-arm commented on scripts/mbedtls_framework/min_requirements.py
> +                                      default_requirement_file)]
Currently we pass an absolute path for `default_requirement_file` and if we were to pass a relative path it would be rather relative to the directory of the caller I'd say thus I am a bit confused by this `path.join`.

2025-01-10 16:08 UTC, valeriosetti commented on scripts/mbedtls_framework/min_requirements.py
> +                                      default_requirement_file)]
Ops, sorry, this is now somehow replicating the work the of the main scripts indeed. Thanks for noticing

2025-01-13 07:52 UTC, ronald-cron-arm approved these changes
LGTM, thanks.

2025-01-13 07:52 UTC, ronald-cron-arm approved these changes

2025-01-13 08:58 UTC, Harry-Ramsey approved these changes
LGTM

2025-01-13 09:01 UTC, ronald-cron-arm commented
Changes approved by the CI of https://github.com/Mbed-TLS/mbedtls/pull/9863, https://github.com/Mbed-TLS/mbedtls/pull/9864 and https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/148.

2025-01-13 09:02 UTC, merged