Enable check_files.py for TF-PSA-Crypto
Mbed-TLS/mbedtls-framework pull request #109
Opened 2024-12-27 10:39 UTC by Harry-Ramsey

This commit enables check_files.py to run for Mbed TLS and TF-PSA-Crypto.

## PR checklist

Please add the numbers (or links) of the associated pull requests for consuming branches. You can omit branches where this pull request is not needed.

- [x] **crypto PR** Mbed-TLS/TF-PSA-Crypto#
- [x] **development PR** Mbed-TLS/mbedtls# : Not required
- [x] **3.6 PR** Mbed-TLS/mbedtls: Not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2025-01-10 11:43 UTC, ronald-cron-arm requested changes
One suggestion otherwise, this looks good to me.

2025-01-10 11:43 UTC, ronald-cron-arm commented on scripts/check_files.py
> +        LICENSE_EXEMPTION_RE_LIST.append(r'(tf-psa-crypto/)?drivers/(?=(everest)/.*)')
For things to be more explicit, I'd say rather something like (not tested):
```python
if build_tree.looks_like_tf_psa_crypto_root(os.getcwd()):
    LICENSE_EXEMPTION_RE_LIST.append(r'drivers/(?=(everest)/.*)')
elif build_tree.is_mbedtls_3_6():
    LICENSE_EXEMPTION_RE_LIST.append(r'3rdparty/(?!(p256-m)/.*)')
```
The script uses `git ls-files` to get the list of files to check and this does not cover submodules. Thus now in mbedtls:development files under `tf-psa-crypto/drivers` are not checked by the script thus no need to update LICENSE_EXEMPTION_RE_LIST in that case.

2025-01-10 12:41 UTC, Harry-Ramsey commented on scripts/check_files.py
> +        LICENSE_EXEMPTION_RE_LIST.append(r'(tf-psa-crypto/)?drivers/(?=(everest)/.*)')
Updated, thanks.

2025-01-10 15:56 UTC, ronald-cron-arm requested changes

2025-01-10 15:56 UTC, ronald-cron-arm commented on scripts/check_files.py
> +        LICENSE_EXEMPTION_RE_LIST.append(r'(tf-psa-crypto/)?drivers/(?=(everest)/.*)')
```suggestion
        LICENSE_EXEMPTION_RE_LIST.append(r'drivers/(?=(everest)/.*)')
```

2025-01-13 13:37 UTC, valeriosetti approved these changes

2025-01-14 10:28 UTC, ronald-cron-arm commented
This looks good to me but we have an issue with the validation for 3.6. Not an issue with this PR but with the 3.6 part of the mbedtls-framework CI in general. I think https://github.com/Mbed-TLS/mbedtls/pull/9902 should fix it. If that the case when https://github.com/Mbed-TLS/mbedtls/pull/9902 is merged the CI of this PR should be all green.

2025-01-15 13:38 UTC, ronald-cron-arm commented
Validated by the CI of https://github.com/Mbed-TLS/mbedtls/pull/9903 for mbedtls-3.6. Ready to be merged.

2025-01-15 13:39 UTC, merged