Use updated config.py classes
Mbed-TLS/mbedtls-framework pull request #35
Opened 2024-07-08 14:42 UTC by gabor-mezei-arm

The `config.py` updated to use the crypto config and this is an update to use these classes.

Related to Mbed-TLS/mbedtls#9158

2024-07-11 13:20 UTC, paul-elliott-arm submitted a review, later dismissed
LGTM

2024-07-16 14:53 UTC, tom-daubney-arm submitted a review, later dismissed
LGTM.

2024-07-19 09:08 UTC, paul-elliott-arm approved these changes
LGTM, on the basis that the `is_3_6` check is going to be very temporary.

2024-07-22 09:52 UTC, tom-daubney-arm submitted a review, later dismissed
LGTM.

2024-07-25 08:45 UTC, gabor-mezei-arm commented
Rebased on `main`

2024-07-26 07:36 UTC, tom-daubney-arm approved these changes
LGTM.

2024-07-29 09:56 UTC, ronald-cron-arm approved these changes
I've checked the rebase from https://github.com/Mbed-TLS/mbedtls-framework/commit/9e218a0689f8a18063d3433965d5e17bc24af1b0 to https://github.com/Mbed-TLS/mbedtls-framework/pull/35/commits/e8b041bcd68c383bb769dba632c01e7503ff0e99.
Approving as @paul-elliott-arm approved https://github.com/Mbed-TLS/mbedtls-framework/commit/9e218a0689f8a18063d3433965d5e17bc24af1b0.

2024-07-30 05:34 UTC, ronald-cron-arm requested changes
Please address the CI failure in https://github.com/Mbed-TLS/mbedtls/pull/9432.

2024-07-31 15:47 UTC, tom-daubney-arm approved these changes
LGTM.

2024-08-01 09:44 UTC, ronald-cron-arm approved these changes

2024-08-01 09:54 UTC, merged