Port `psa_exercise_key()` changes added mid-framework-move
Mbed-TLS/mbedtls-framework pull request #78
Opened 2024-11-18 16:36 UTC by davidhorstmann-arm

These changes to `psa_exercise_key` were added while the files were being moved to the framework. Port them to the framework now.

2024-11-18 16:53 UTC, eleuzi01 submitted a review, later dismissed
LGTM, all the relevant changes from [#9602](https://github.com/Mbed-TLS/mbedtls/pull/9602) seem to be ported

2024-11-19 08:27 UTC, mpg approved these changes
LGTM, I checked that all the changes that were made in development after the file was moved here are present.

2024-11-19 09:24 UTC, mpg requested changes

2024-11-19 09:24 UTC, mpg commented on tests/src/psa_exercise_key.c
> +    status = psa_key_agreement(key, public_key, public_key_length, alg,
Actually this won't work for 3.6, so we'll need some guards, see https://github.com/Mbed-TLS/mbedtls/pull/9766#issuecomment-2485052543

2024-11-20 08:36 UTC, mpg approved these changes
LGTM, thanks!

2024-11-20 08:37 UTC, mpg commented
CI is green on https://github.com/Mbed-TLS/mbedtls/pull/9756 and https://github.com/Mbed-TLS/mbedtls/pull/9766 so the result here can be ignored.

2024-11-20 09:10 UTC, eleuzi01 approved these changes
LGTM

2024-11-20 09:55 UTC, merged