all-core/helpers: Added support for libtestdriver post repo split
Mbed-TLS/mbedtls-framework pull request #85
Opened 2024-11-28 22:55 UTC by minosgalanakis

This pr changes the helper scripts to point to the ts-psa-crypto configuration file used after the repository split.

Development: https://github.com/Mbed-TLS/mbedtls/pull/9567

2024-11-29 14:52 UTC, minosgalanakis commented on scripts/all-core.sh
> +            if in_3_6_branch; then
I feel that the branch detection logic here is redudant, but I added it for now.

2024-12-03 08:24 UTC, ronald-cron-arm requested changes

2024-12-03 08:24 UTC, ronald-cron-arm commented on scripts/all-core.sh
> +            fi
While at it, I'd suggest something like:
```
    if in_mbedtls_repo; then                                                    
        CONFIG_H='include/mbedtls/mbedtls_config.h'                             
        if in_3_6_branch; then                                                                    
            CRYPTO_CONFIG_H='include/psa/crypto_config.h'                       
            # helper_armc6_build_test() relies on these being defined,          
            # but empty if the paths don't exist (as in 3.6).                   
            PSA_CORE_PATH=''                                                    
            BUILTIN_SRC_PATH=''                                                                                               
            CONFIG_TEST_DRIVER_H='tests/configs/config_test_driver.h'                                                                  
        else                                           
            CRYPTO_CONFIG_H='tf-psa-crypto/include/psa/crypto_config.h'         
            PSA_CORE_PATH='tf-psa-crypto/core'                                  
            BUILTIN_SRC_PATH='tf-psa-crypto/drivers/builtin/src'                
            CONFIG_TEST_DRIVER_H='tf-psa-crypto/tests/configs/crypto_config_test_driver.h'                                                                  
        fi                                                                    
        config_files="$CONFIG_H $CRYPTO_CONFIG_H $CONFIG_TEST_DRIVER_H"         
    else
```

2024-12-03 13:34 UTC, gabor-mezei-arm reviewed
Besides Ronald's suggestion it looks good to me.

2024-12-03 18:37 UTC, ronald-cron-arm approved these changes
LGTM. The CI validates the changes for 3.6, the CI of #9567 validates the changes for development.

2024-12-04 07:30 UTC, ronald-cron-arm commented
@gabor-mezei-arm please have another look.

2024-12-04 10:26 UTC, gabor-mezei-arm approved these changes
LGTM

2024-12-04 14:27 UTC, merged