Move "easy" basic checks scripts to the framework
Mbed-TLS/mbedtls-framework pull request #95
Opened 2024-12-05 19:43 UTC by valeriosetti

Resolves #69

2024-12-09 15:56 UTC, eleuzi01 commented
Looks good, however given this https://github.com/Mbed-TLS/mbedtls-framework/pull/80#issuecomment-2527502271 might need to move files from `tests/scripts` to just `scripts`

2024-12-11 12:51 UTC, eleuzi01 commented on scripts/recursion.pl
> +# Typical usage: scripts/recursion.pl library/*.c
Wouldn't this be 
```suggestion
# Typical usage: framework/scripts/recursion.pl library/*.c
```
now that it's moved?

2024-12-16 12:14 UTC, eleuzi01 submitted a review, later dismissed
LGTM, thanks!

2025-01-07 15:37 UTC, ronald-cron-arm requested changes
One suggestion, otherwise as already mentioned you probably need to rebase on top of main head.

2025-01-08 09:47 UTC, ronald-cron-arm approved these changes
LGTM, thanks.

2025-01-08 11:09 UTC, eleuzi01 approved these changes
LGTM, thanks!

2025-01-08 12:08 UTC, merged